name: Image Scan with Trivy

on:
  push:
    branches:
      - main
    pull_request:
        branches:
            - main

  jobs:
    scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build -t my-image .

        - name: Run Trivy vulnerability scan on local image
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: my-image
            format: 'sarif'
            output: 'trivy-scan-results.sarif'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'CRITICAL,HIGH,MEDIUM'

        - name: Upload Trivy scan results
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: trivy-scan-results.sarif # Ensure this matches the output file from Trivy
            category: 'security'
          if: always() # Always upload results, even if the scan fails


    build:
      runs-on: ubuntu-latest
      needs: scan
      if: success() # Only run if the scan job was successful
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          id: docker_build
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/my-image:latest # Replace with your image name
            platforms: linux/amd64,linux/arm64
            cache-from: type=gha,scope=build-and-scan
            cache-to: type=gha,mode=max,scope=build-and-scan


